use super::*;

#[test]
fn compose_appends_block_to_existing_content() {
    let composed = compose(
        "# My notes\n\nHand-written.\n",
        "# Rules\n\n## Foo\n\nbody\n",
    );
    assert!(composed.starts_with("# My notes\n\nHand-written.\n\n"));
    assert!(composed.contains(BEGIN_MARKER));
    assert!(composed.contains("## Foo"));
    assert!(composed.trim_end().ends_with(END_MARKER));
}

#[test]
fn compose_is_idempotent() {
    let block = "# Rules\n\n## Foo\n\nbody\n";
    let once = compose("preamble\n", block);
    let twice = compose(&once, block);
    assert_eq!(once, twice);
}

#[test]
fn compose_replaces_only_the_generated_region() {
    let block = "# Rules\n\n## Foo\n\nnew body\n";
    let first = compose("keep me above\n", "# Rules\n\n## Foo\n\nold body\n");
    let updated = compose(&format!("{first}\nkeep me below\n"), block);
    assert!(updated.contains("keep me above"));
    assert!(updated.contains("keep me below"));
    assert!(updated.contains("new body"));
    assert!(!updated.contains("old body"));
    assert_eq!(updated.matches(BEGIN_MARKER).count(), 1);
}

#[test]
fn compose_supersedes_the_legacy_block() {
    let legacy = "# top\n\n<!-- harness-rules:begin (generated by forge-provision) -->\n\nold rules\n\n<!-- harness-rules:end -->\n\n# bottom\n";
    let composed = compose(legacy, "# Rules\n\n## New\n\nfresh\n");
    assert!(!composed.contains("harness-rules:begin"));
    assert!(!composed.contains("old rules"));
    assert!(composed.contains("# top"));
    assert!(composed.contains("# bottom"));
    assert!(composed.contains("## New"));
    assert_eq!(composed.matches(BEGIN_MARKER).count(), 1);
}

#[test]
fn write_block_creates_file_with_only_the_block() {
    let dir = tempfile::tempdir().expect("tempdir");
    let file = dir.path().join("AGENTS.md");
    write_block(&file, "# Rules\n\n## Foo\n\nbody\n").expect("write");
    let content = std::fs::read_to_string(&file).expect("read");
    assert!(content.starts_with(BEGIN_MARKER));
    assert!(content.contains("## Foo"));
}

#[test]
fn write_block_is_a_noop_when_unchanged() {
    let dir = tempfile::tempdir().expect("tempdir");
    let file = dir.path().join("AGENTS.md");
    let block = "# Rules\n\n## Foo\n\nbody\n";
    write_block(&file, block).expect("first write");
    let first = std::fs::metadata(&file)
        .and_then(|m| m.modified())
        .expect("mtime");
    write_block(&file, block).expect("second write");
    let second = std::fs::metadata(&file)
        .and_then(|m| m.modified())
        .expect("mtime");
    assert_eq!(first, second, "unchanged block must not rewrite the file");
}

#[test]
fn render_block_inlines_sorted_rules() {
    let dir = tempfile::tempdir().expect("tempdir");
    std::fs::write(dir.path().join("Beta.md"), "beta body\n").expect("beta");
    std::fs::write(dir.path().join("Alpha.md"), "alpha body\n").expect("alpha");
    std::fs::write(dir.path().join("ignore.txt"), "not a rule\n").expect("txt");
    let block = render_block(dir.path()).expect("block");
    let alpha = block.find("## Alpha").expect("alpha heading");
    let beta = block.find("## Beta").expect("beta heading");
    assert!(alpha < beta, "rules sorted by name");
    assert!(block.contains("alpha body"));
    assert!(!block.contains("not a rule"));
}

#[test]
fn render_block_is_none_without_rules() {
    let dir = tempfile::tempdir().expect("tempdir");
    assert!(render_block(dir.path()).is_none());
}

#[test]
fn ensure_opencode_instruction_preserves_unknown_keys_and_entries() {
    let dir = tempfile::tempdir().expect("tempdir");
    let config = dir.path().join("opencode.json");
    std::fs::write(
        &config,
        r#"{"$schema":"https://opencode.ai/config.json","model":"x","instructions":["existing.md"]}"#,
    )
    .expect("seed");
    ensure_opencode_instruction(&config, "/home/rules/*.md").expect("wire");
    let document: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&config).expect("read")).expect("json");
    assert_eq!(document["model"], "x");
    let instructions = document["instructions"].as_array().expect("array");
    assert!(instructions.iter().any(|v| v == "existing.md"));
    assert!(instructions.iter().any(|v| v == "/home/rules/*.md"));
}

#[test]
fn ensure_opencode_instruction_is_idempotent() {
    let dir = tempfile::tempdir().expect("tempdir");
    let config = dir.path().join("opencode.json");
    ensure_opencode_instruction(&config, "/home/rules/*.md").expect("first");
    let first = std::fs::read_to_string(&config).expect("read");
    ensure_opencode_instruction(&config, "/home/rules/*.md").expect("second");
    let second = std::fs::read_to_string(&config).expect("read");
    assert_eq!(first, second);
    let document: serde_json::Value = serde_json::from_str(&second).expect("json");
    let count = document["instructions"]
        .as_array()
        .expect("array")
        .iter()
        .filter(|v| *v == "/home/rules/*.md")
        .count();
    assert_eq!(count, 1, "glob added once");
}

#[test]
fn ensure_opencode_instruction_creates_missing_file() {
    let dir = tempfile::tempdir().expect("tempdir");
    let config = dir.path().join("nested").join("opencode.json");
    ensure_opencode_instruction(&config, "/home/rules/*.md").expect("create");
    let document: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&config).expect("read")).expect("json");
    assert!(
        document["instructions"]
            .as_array()
            .expect("array")
            .iter()
            .any(|v| v == "/home/rules/*.md")
    );
}
