//! Rule wiring for harnesses that do not read a rules directory.
//!
//! Only Claude Code loads `~/.claude/rules/`. Codex reads its AGENTS.md chain,
//! Gemini CLI its GEMINI.md hierarchy, and opencode an `instructions` array;
//! none scans a rules directory, and no harness expands `@`-imports the way we
//! would need. So the assembled rule bodies are inlined into each harness's
//! own instruction file inside one marker-delimited generated block,
//! regenerated on every install. Content outside the markers is never touched.

use rune::error::{Error, ErrorKind};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

pub const BEGIN_MARKER: &str =
    "<!-- rune-rules:begin (generated by `rune install`; do not edit by hand) -->";
pub const END_MARKER: &str = "<!-- rune-rules:end -->";
/// The forge-provision block this supersedes; replaced by the rune block on
/// first run so exactly one generated region survives.
const LEGACY_BEGIN: &str = "<!-- harness-rules:begin";
const LEGACY_END: &str = "<!-- harness-rules:end -->";

/// The marker-key under which a harness's generated block is fingerprinted in
/// the provider manifest, so drift and doctor can spot a stale block.
pub const WIRING_MANIFEST_KEY: &str = ".rune-wiring";

/// Render the generated block body from the deployed rule files. Rules land at
/// `<rules_dir>/*.md`; each is inlined under an `##` heading named by its stem,
/// sorted for a stable block. Returns `None` when no rules are present.
pub fn render_block(rules_dir: &Path) -> Option<String> {
    let mut rules: BTreeMap<String, String> = BTreeMap::new();
    let entries = fs::read_dir(rules_dir).ok()?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("md") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        if let Ok(body) = fs::read_to_string(&path) {
            rules.insert(stem.to_string(), body);
        }
    }
    if rules.is_empty() {
        return None;
    }

    let mut block = String::from("# Rules\n");
    for (stem, body) in rules {
        block.push_str("\n## ");
        block.push_str(&stem);
        block.push_str("\n\n");
        block.push_str(body.trim_end_matches('\n'));
        block.push('\n');
    }
    Some(block)
}

/// A file split into the text before a generated region, the region's own
/// body (ignored), and the text after. Absence of a region leaves `before`
/// holding the whole file and `after` empty.
struct Split {
    before: String,
    after: String,
}

fn find_region(content: &str, begin: &str, end: &str) -> Option<(usize, usize)> {
    let start = content.find(begin)?;
    let after_begin = start + begin.len();
    let end_rel = content[after_begin..].find(end)?;
    Some((start, after_begin + end_rel + end.len()))
}

fn split_around_generated(content: &str) -> Split {
    // The rune block wins; failing that, adopt the legacy forge-provision
    // block's location so the two never coexist.
    let region = find_region(content, BEGIN_MARKER, END_MARKER)
        .or_else(|| find_region(content, LEGACY_BEGIN, LEGACY_END));
    match region {
        Some((start, end)) => Split {
            before: content[..start].to_string(),
            after: content[end..].to_string(),
        },
        None => Split {
            before: content.to_string(),
            after: String::new(),
        },
    }
}

/// The full file content with the generated block replacing any existing
/// region, or appended when none exists. Deterministic given the same block,
/// so re-running install is a no-op when nothing changed.
pub fn compose(existing: &str, block: &str) -> String {
    let split = split_around_generated(existing);
    let mut before = split.before;
    // One blank line before the block unless the file is empty.
    if !before.is_empty() {
        while before.ends_with('\n') {
            before.pop();
        }
        if !before.is_empty() {
            before.push_str("\n\n");
        }
    }
    let mut after = split.after;
    while after.starts_with('\n') {
        after.remove(0);
    }

    let mut composed = before;
    composed.push_str(BEGIN_MARKER);
    composed.push('\n');
    composed.push('\n');
    composed.push_str(block);
    composed.push('\n');
    composed.push_str(END_MARKER);
    composed.push('\n');
    if !after.is_empty() {
        composed.push('\n');
        composed.push_str(&after);
    }
    composed
}

/// Write `block` into `file` inside the generated region, creating the file
/// with only the block when it does not exist. Refuses a symlinked target.
pub fn write_block(file: &Path, block: &str) -> Result<(), Error> {
    if file.symlink_metadata().is_ok_and(|meta| meta.is_symlink()) {
        return Err(Error::new(
            ErrorKind::Config,
            format!(
                "{} is a symlink; refusing to wire through it",
                file.display()
            ),
        ));
    }
    let existing = match fs::read_to_string(file) {
        Ok(content) => content,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(error) => {
            return Err(Error::new(
                ErrorKind::Io,
                format!("cannot read {}: {error}", file.display()),
            ));
        }
    };
    let composed = compose(&existing, block);
    if composed == existing {
        return Ok(());
    }
    if let Some(parent) = file.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            Error::new(
                ErrorKind::Io,
                format!("cannot create {}: {error}", parent.display()),
            )
        })?;
    }
    crate::cli::config::write_atomic(file, &composed)
}

/// Ensure `glob` is present in the `instructions` array of an opencode config
/// file, preserving every other key and existing entry. Creates the array or
/// the file when missing.
pub fn ensure_opencode_instruction(config_file: &Path, glob: &str) -> Result<(), Error> {
    if config_file
        .symlink_metadata()
        .is_ok_and(|meta| meta.is_symlink())
    {
        return Err(Error::new(
            ErrorKind::Config,
            format!(
                "{} is a symlink; refusing to wire through it",
                config_file.display()
            ),
        ));
    }
    let mut document: serde_json::Value = match fs::read_to_string(config_file) {
        Ok(content) => serde_json::from_str(&content).map_err(|error| {
            Error::new(
                ErrorKind::Config,
                format!("{} is not valid JSON: {error}", config_file.display()),
            )
        })?,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            serde_json::json!({ "$schema": "https://opencode.ai/config.json" })
        }
        Err(error) => {
            return Err(Error::new(
                ErrorKind::Io,
                format!("cannot read {}: {error}", config_file.display()),
            ));
        }
    };

    let object = document.as_object_mut().ok_or_else(|| {
        Error::new(
            ErrorKind::Config,
            format!("{} is not a JSON object", config_file.display()),
        )
    })?;
    let instructions = object
        .entry("instructions")
        .or_insert_with(|| serde_json::Value::Array(Vec::new()));
    let array = instructions.as_array_mut().ok_or_else(|| {
        Error::new(
            ErrorKind::Config,
            format!("{}: `instructions` is not an array", config_file.display()),
        )
    })?;
    if array.iter().any(|entry| entry.as_str() == Some(glob)) {
        return Ok(());
    }
    array.push(serde_json::Value::String(glob.to_string()));

    let mut rendered = serde_json::to_string_pretty(&document).map_err(|error| {
        Error::new(
            ErrorKind::Config,
            format!("cannot render {}: {error}", config_file.display()),
        )
    })?;
    rendered.push('\n');
    if let Some(parent) = config_file.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            Error::new(
                ErrorKind::Io,
                format!("cannot create {}: {error}", parent.display()),
            )
        })?;
    }
    crate::cli::config::write_atomic(config_file, &rendered)
}

#[cfg(test)]
mod tests;
