use super::{ContentKind, ProviderConfig};
use crate::manifest;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsStr;
use std::fs;
use std::path::{Component, Path, PathBuf};

pub const CONFIG_SOURCE: &str = "bundled";

const REGISTRY_VERSION: u32 = 1;
const VIRTUAL_WIRING_ENTRY: &str = ".rune-wiring";
const WIRING_BEGIN_MARKER: &str =
    "<!-- rune-rules:begin (generated by `rune install`; do not edit by hand) -->";
const WIRING_END_MARKER: &str = "<!-- rune-rules:end -->";
const MANAGED_DIRECTORIES: &[&str] = &["agents", "skills", "rules", "hooks"];
const EMBEDDED_REGISTRY: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/provider-detection.yaml"
));

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DetectionRule {
    pub executable: Option<String>,
    #[serde(default)]
    pub config_directories: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RegistryDocument {
    version: u32,
    providers: BTreeMap<String, DetectionRule>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceKind {
    Executable,
    ConfigDirectory,
    DeploymentManifest,
    ManagedFile,
}

impl EvidenceKind {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Executable => "executable",
            Self::ConfigDirectory => "config directory",
            Self::DeploymentManifest => "deployment manifest",
            Self::ManagedFile => "managed file",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceResult {
    Found,
    NotFound,
    Current,
    Outdated,
    Missing,
    Modified,
    Invalid,
    Unreadable,
}

impl EvidenceResult {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Found => "found",
            Self::NotFound => "not found",
            Self::Current => "current",
            Self::Outdated => "outdated",
            Self::Missing => "missing",
            Self::Modified => "modified",
            Self::Invalid => "invalid",
            Self::Unreadable => "unreadable",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct DetectionEvidence {
    pub kind: EvidenceKind,
    pub value: String,
    pub result: EvidenceResult,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum DeploymentState {
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "not installed")]
    NotInstalled,
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "outdated")]
    Outdated,
    #[serde(rename = "needs repair")]
    NeedsRepair,
    #[serde(rename = "modified")]
    Modified,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RecommendedAction {
    None,
    Enable,
    Install,
    Repair,
    Review,
}

impl DeploymentState {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Disabled => "disabled",
            Self::NotInstalled => "not installed",
            Self::Current => "current",
            Self::Outdated => "outdated",
            Self::NeedsRepair => "needs repair",
            Self::Modified => "modified",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProviderDetection {
    pub provider: String,
    pub target: PathBuf,
    pub evidence: Vec<DetectionEvidence>,
    pub deployment_state: DeploymentState,
    pub recommended_action: RecommendedAction,
}

impl ProviderDetection {
    #[must_use]
    pub fn has_manifest(&self) -> bool {
        self.evidence.iter().any(|evidence| {
            evidence.kind == EvidenceKind::DeploymentManifest
                && evidence.result != EvidenceResult::NotFound
        })
    }

    #[must_use]
    pub fn is_detected(&self) -> bool {
        self.has_manifest()
            || self.evidence.iter().any(|evidence| {
                matches!(
                    evidence.kind,
                    EvidenceKind::Executable | EvidenceKind::ConfigDirectory
                ) && evidence.result == EvidenceResult::Found
            })
    }
}

pub fn bundled_registry() -> Result<BTreeMap<String, DetectionRule>, String> {
    parse_registry(EMBEDDED_REGISTRY)
}

fn parse_registry(content: &str) -> Result<BTreeMap<String, DetectionRule>, String> {
    let document: RegistryDocument = serde_yaml::from_str(content)
        .map_err(|error| format!("failed to parse provider detection registry: {error}"))?;
    if document.version != REGISTRY_VERSION {
        return Err(format!(
            "unsupported provider detection registry version {}; expected {REGISTRY_VERSION}",
            document.version
        ));
    }
    if document.providers.is_empty() {
        return Err("provider detection registry has no providers".to_string());
    }
    for (name, rule) in &document.providers {
        validate_rule(name, rule)?;
    }
    Ok(document.providers)
}

fn validate_rule(name: &str, rule: &DetectionRule) -> Result<(), String> {
    if name.is_empty() {
        return Err("provider detection registry has an empty provider name".to_string());
    }
    if let Some(executable) = &rule.executable {
        let path = Path::new(executable);
        let valid = !executable.is_empty()
            && path.components().count() == 1
            && matches!(path.components().next(), Some(Component::Normal(_)));
        if !valid {
            return Err(format!(
                "provider '{name}' has an invalid executable name: {executable}"
            ));
        }
    }
    if rule.executable.is_none() && rule.config_directories.is_empty() {
        return Err(format!("provider '{name}' has no bounded evidence"));
    }
    for directory in &rule.config_directories {
        let path = Path::new(directory);
        let valid = !directory.is_empty()
            && !path.is_absolute()
            && path
                .components()
                .all(|component| matches!(component, Component::Normal(_)));
        if !valid {
            return Err(format!(
                "provider '{name}' has an invalid config directory: {directory}"
            ));
        }
    }
    Ok(())
}

pub fn detect_provider(
    name: &str,
    rule: &DetectionRule,
    config: &ProviderConfig,
    source_root: &Path,
    target_base: &Path,
    home: &Path,
    search_path: Option<&OsStr>,
) -> ProviderDetection {
    let default_target = resolve_target(target_base, config.default_target());
    let mut evidence = Vec::new();
    append_bundled_evidence(rule, target_base, search_path, &mut evidence);
    let mut flags = DetectionFlags::default();
    let mut manifests = BTreeMap::new();
    let mut missing_targets = Vec::new();
    for target_root in resolved_target_roots(config, target_base) {
        match load_manifest_entries(target_base, &target_root, &mut flags, &mut evidence) {
            ManifestLoad::Entries(entries) => {
                flags.manifest_roots += 1;
                inspect_manifest_entries(
                    name,
                    config,
                    source_root,
                    target_base,
                    home,
                    &target_root,
                    &entries,
                    &mut flags,
                    &mut evidence,
                );
                manifests.insert(target_root, entries);
            }
            ManifestLoad::Missing => missing_targets.push(target_root),
            ManifestLoad::Invalid => {}
        }
    }
    if flags.manifest_roots > 0 {
        for target in missing_targets {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Install,
                &target,
            );
        }
        inspect_build_tree(
            name,
            config,
            source_root,
            target_base,
            &manifests,
            &mut flags,
            &mut evidence,
        );
    }

    let deployment_state = reduce_state(config, &flags);
    let recommended_action = recommended_action(deployment_state, &flags);
    let target = flags
        .issue
        .as_ref()
        .map_or(default_target, |issue| issue.target.clone());
    ProviderDetection {
        provider: name.to_string(),
        target,
        evidence,
        deployment_state,
        recommended_action,
    }
}

fn append_bundled_evidence(
    rule: &DetectionRule,
    target_base: &Path,
    search_path: Option<&OsStr>,
    evidence: &mut Vec<DetectionEvidence>,
) {
    if let Some(executable) = &rule.executable {
        let found = executable_on_path(executable, search_path);
        evidence.push(DetectionEvidence {
            kind: EvidenceKind::Executable,
            value: executable.clone(),
            result: if found {
                EvidenceResult::Found
            } else {
                EvidenceResult::NotFound
            },
        });
    }

    for directory in &rule.config_directories {
        let path = target_base.join(directory);
        let found = path.is_dir();
        evidence.push(DetectionEvidence {
            kind: EvidenceKind::ConfigDirectory,
            value: path.to_string_lossy().into_owned(),
            result: if found {
                EvidenceResult::Found
            } else {
                EvidenceResult::NotFound
            },
        });
    }
}

fn resolved_target_roots(config: &ProviderConfig, target_base: &Path) -> Vec<PathBuf> {
    let mut targets = config
        .target_roots()
        .into_iter()
        .map(|root| resolve_target(target_base, root))
        .collect::<Vec<_>>();
    targets.sort();
    targets.dedup();
    targets
}

#[derive(Debug, Default)]
struct DetectionFlags {
    manifest_roots: usize,
    issue: Option<DetectionIssue>,
}

impl DetectionFlags {
    fn record(&mut self, severity: IssueSeverity, action: RecommendedAction, target: &Path) {
        let replace = self.issue.as_ref().is_none_or(|current| {
            severity.priority() > current.severity.priority()
                || (severity == current.severity && action.priority() > current.action.priority())
        });
        if replace {
            self.issue = Some(DetectionIssue {
                severity,
                action,
                target: target.to_path_buf(),
            });
        }
    }
}

#[derive(Debug)]
struct DetectionIssue {
    severity: IssueSeverity,
    action: RecommendedAction,
    target: PathBuf,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum IssueSeverity {
    Outdated,
    NeedsRepair,
    Modified,
}

impl IssueSeverity {
    const fn priority(self) -> u8 {
        match self {
            Self::Outdated => 1,
            Self::NeedsRepair => 2,
            Self::Modified => 3,
        }
    }
}

impl RecommendedAction {
    const fn priority(self) -> u8 {
        match self {
            Self::None | Self::Enable => 0,
            Self::Repair => 1,
            Self::Install => 2,
            Self::Review => 3,
        }
    }
}

enum ManifestLoad {
    Missing,
    Invalid,
    Entries(BTreeMap<String, manifest::ManifestEntry>),
}

fn load_manifest_entries(
    target_base: &Path,
    target_root: &Path,
    flags: &mut DetectionFlags,
    evidence: &mut Vec<DetectionEvidence>,
) -> ManifestLoad {
    let manifest_path = target_root.join(".manifest");
    match inspect_target_path(target_base, target_root) {
        PathInspection::Safe => {}
        PathInspection::Symlink(path) => {
            flags.record(
                IssueSeverity::Modified,
                RecommendedAction::Review,
                target_root,
            );
            push_manifest_evidence(evidence, &path, EvidenceResult::Modified);
            return ManifestLoad::Invalid;
        }
        PathInspection::Unreadable(path) => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            push_manifest_evidence(evidence, &path, EvidenceResult::Unreadable);
            return ManifestLoad::Invalid;
        }
    }
    match fs::symlink_metadata(&manifest_path) {
        Ok(metadata) if metadata.is_file() && !metadata.is_symlink() => {}
        Ok(metadata) if metadata.is_symlink() => {
            flags.record(
                IssueSeverity::Modified,
                RecommendedAction::Review,
                target_root,
            );
            push_manifest_evidence(evidence, &manifest_path, EvidenceResult::Modified);
            return ManifestLoad::Invalid;
        }
        Ok(_) => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            push_manifest_evidence(evidence, &manifest_path, EvidenceResult::Invalid);
            return ManifestLoad::Invalid;
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            push_manifest_evidence(evidence, &manifest_path, EvidenceResult::NotFound);
            return ManifestLoad::Missing;
        }
        Err(_) => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            push_manifest_evidence(evidence, &manifest_path, EvidenceResult::Unreadable);
            return ManifestLoad::Invalid;
        }
    }
    let Ok(content) = fs::read_to_string(&manifest_path) else {
        flags.record(
            IssueSeverity::NeedsRepair,
            RecommendedAction::Review,
            target_root,
        );
        push_manifest_evidence(evidence, &manifest_path, EvidenceResult::Unreadable);
        return ManifestLoad::Invalid;
    };
    let Ok(entries) = manifest::read(&content) else {
        flags.record(
            IssueSeverity::NeedsRepair,
            RecommendedAction::Review,
            target_root,
        );
        push_manifest_evidence(evidence, &manifest_path, EvidenceResult::Invalid);
        return ManifestLoad::Invalid;
    };
    push_manifest_evidence(evidence, &manifest_path, EvidenceResult::Found);
    ManifestLoad::Entries(entries.into_iter().collect())
}

fn push_manifest_evidence(
    evidence: &mut Vec<DetectionEvidence>,
    manifest_path: &Path,
    result: EvidenceResult,
) {
    evidence.push(DetectionEvidence {
        kind: EvidenceKind::DeploymentManifest,
        value: manifest_path.to_string_lossy().into_owned(),
        result,
    });
}

#[allow(clippy::too_many_arguments)]
fn inspect_manifest_entries(
    provider: &str,
    config: &ProviderConfig,
    source_root: &Path,
    target_base: &Path,
    home: &Path,
    target_root: &Path,
    entries: &BTreeMap<String, manifest::ManifestEntry>,
    flags: &mut DetectionFlags,
    evidence: &mut Vec<DetectionEvidence>,
) {
    for (relative, entry) in entries {
        if relative == VIRTUAL_WIRING_ENTRY {
            if valid_digest(&entry.fingerprint) {
                let wiring = inspect_wiring(
                    provider,
                    source_root,
                    home,
                    target_root,
                    &entry.fingerprint,
                    flags,
                );
                evidence.push(wiring);
            } else {
                flags.record(
                    IssueSeverity::NeedsRepair,
                    RecommendedAction::Review,
                    target_root,
                );
                evidence.push(DetectionEvidence {
                    kind: EvidenceKind::ManagedFile,
                    value: target_root.join(relative).to_string_lossy().into_owned(),
                    result: EvidenceResult::Invalid,
                });
            }
            continue;
        }
        let expected_target = expected_target(config, target_base, relative);
        if expected_target.as_deref() != Some(target_root) || !valid_digest(&entry.fingerprint) {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            evidence.push(DetectionEvidence {
                kind: EvidenceKind::ManagedFile,
                value: target_root.join(relative).to_string_lossy().into_owned(),
                result: EvidenceResult::Invalid,
            });
            continue;
        }
        let deployed_path = target_root.join(relative);
        let result = managed_file_result(
            provider,
            source_root,
            target_root,
            &deployed_path,
            relative,
            &entry.fingerprint,
            flags,
        );
        evidence.push(DetectionEvidence {
            kind: EvidenceKind::ManagedFile,
            value: deployed_path.to_string_lossy().into_owned(),
            result,
        });
    }
}

#[allow(clippy::too_many_arguments)]
fn managed_file_result(
    provider: &str,
    source_root: &Path,
    target_root: &Path,
    deployed_path: &Path,
    relative: &str,
    expected_digest: &str,
    flags: &mut DetectionFlags,
) -> EvidenceResult {
    match inspect_relative_path(target_root, relative) {
        PathInspection::Safe => {}
        PathInspection::Symlink(_) | PathInspection::Unreadable(_) => {
            flags.record(
                IssueSeverity::Modified,
                RecommendedAction::Review,
                target_root,
            );
            return EvidenceResult::Modified;
        }
    }
    match fs::symlink_metadata(deployed_path) {
        Ok(metadata) if metadata.is_symlink() || !metadata.is_file() => {
            flags.record(
                IssueSeverity::Modified,
                RecommendedAction::Review,
                target_root,
            );
            return EvidenceResult::Modified;
        }
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            let build_path = source_root.join("build").join(provider).join(relative);
            let build_relative = format!("build/{provider}/{relative}");
            let action = if matches!(
                inspect_relative_path(source_root, &build_relative),
                PathInspection::Safe
            ) && read_regular_file(&build_path)
                .is_ok_and(|bytes| manifest::content_sha256_bytes(&bytes) == expected_digest)
            {
                RecommendedAction::Repair
            } else {
                RecommendedAction::Review
            };
            flags.record(IssueSeverity::NeedsRepair, action, target_root);
            return EvidenceResult::Missing;
        }
        Err(_) => {
            flags.record(
                IssueSeverity::Modified,
                RecommendedAction::Review,
                target_root,
            );
            return EvidenceResult::Modified;
        }
    }
    let Ok(bytes) = fs::read(deployed_path) else {
        flags.record(
            IssueSeverity::Modified,
            RecommendedAction::Review,
            target_root,
        );
        return EvidenceResult::Modified;
    };
    if manifest::content_sha256_bytes(&bytes) != expected_digest {
        flags.record(
            IssueSeverity::Modified,
            RecommendedAction::Review,
            target_root,
        );
        return EvidenceResult::Modified;
    }
    EvidenceResult::Current
}

fn reduce_state(config: &ProviderConfig, flags: &DetectionFlags) -> DeploymentState {
    if flags
        .issue
        .as_ref()
        .is_some_and(|issue| issue.severity == IssueSeverity::Modified)
    {
        DeploymentState::Modified
    } else if !config.enabled {
        DeploymentState::Disabled
    } else {
        match flags.issue.as_ref().map(|issue| issue.severity) {
            Some(IssueSeverity::NeedsRepair) => DeploymentState::NeedsRepair,
            Some(IssueSeverity::Outdated) => DeploymentState::Outdated,
            Some(IssueSeverity::Modified) => DeploymentState::Modified,
            None if flags.manifest_roots > 0 => DeploymentState::Current,
            None => DeploymentState::NotInstalled,
        }
    }
}

fn recommended_action(state: DeploymentState, flags: &DetectionFlags) -> RecommendedAction {
    match state {
        DeploymentState::Disabled => RecommendedAction::Enable,
        DeploymentState::NotInstalled | DeploymentState::Outdated => RecommendedAction::Install,
        DeploymentState::Current => RecommendedAction::None,
        DeploymentState::Modified => RecommendedAction::Review,
        DeploymentState::NeedsRepair => flags
            .issue
            .as_ref()
            .map_or(RecommendedAction::Review, |issue| issue.action),
    }
}

#[derive(Debug)]
enum PathInspection {
    Safe,
    Symlink(PathBuf),
    Unreadable(PathBuf),
}

fn inspect_target_path(base: &Path, target: &Path) -> PathInspection {
    let Ok(relative) = target.strip_prefix(base) else {
        return inspect_absolute_path(target);
    };
    if relative.as_os_str().is_empty() {
        return inspect_one_path(target);
    }
    let mut current = base.to_path_buf();
    for component in relative.components() {
        if !matches!(component, Component::Normal(_)) {
            return PathInspection::Unreadable(current.join(component.as_os_str()));
        }
        current.push(component.as_os_str());
        match inspect_one_path(&current) {
            PathInspection::Safe => {}
            issue => return issue,
        }
    }
    PathInspection::Safe
}

fn inspect_absolute_path(path: &Path) -> PathInspection {
    let mut current = PathBuf::new();
    for component in path.components() {
        if matches!(component, Component::ParentDir | Component::CurDir) {
            return PathInspection::Unreadable(current.join(component.as_os_str()));
        }
        current.push(component.as_os_str());
        match inspect_one_path(&current) {
            PathInspection::Safe => {}
            issue => return issue,
        }
    }
    PathInspection::Safe
}

fn inspect_relative_path(root: &Path, relative: &str) -> PathInspection {
    let mut current = root.to_path_buf();
    for component in Path::new(relative).components() {
        current.push(component.as_os_str());
        match inspect_one_path(&current) {
            PathInspection::Safe => {}
            issue => return issue,
        }
    }
    PathInspection::Safe
}

fn inspect_one_path(path: &Path) -> PathInspection {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.is_symlink() => PathInspection::Symlink(path.to_path_buf()),
        Ok(_) => PathInspection::Safe,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => PathInspection::Safe,
        Err(_) => PathInspection::Unreadable(path.to_path_buf()),
    }
}

fn expected_target(config: &ProviderConfig, target_base: &Path, relative: &str) -> Option<PathBuf> {
    if !is_managed_relative(relative) {
        return None;
    }
    if relative.starts_with(".claude-plugin/") {
        return Some(resolve_target(target_base, config.default_target()));
    }
    let kind = kind_for_relative(relative)?;
    Some(resolve_target(target_base, config.target_for_kind(kind)))
}

fn kind_for_relative(relative: &str) -> Option<ContentKind> {
    match relative.split_once('/').map(|(kind, _)| kind) {
        Some("agents") => Some(ContentKind::Agents),
        Some("skills") => Some(ContentKind::Skills),
        Some("rules") => Some(ContentKind::Rules),
        Some("hooks") => Some(ContentKind::Hooks),
        _ => None,
    }
}

fn valid_digest(digest: &str) -> bool {
    digest.len() == 64
        && digest
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn inspect_wiring(
    provider: &str,
    source_root: &Path,
    home: &Path,
    target_root: &Path,
    expected_digest: &str,
    flags: &mut DetectionFlags,
) -> DetectionEvidence {
    if provider == "opencode" {
        return inspect_opencode_wiring(home, target_root, expected_digest, flags);
    }
    let instruction_name = match provider {
        "codex" => "AGENTS.md",
        "gemini" => "GEMINI.md",
        _ => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            return DetectionEvidence {
                kind: EvidenceKind::ManagedFile,
                value: target_root
                    .join(VIRTUAL_WIRING_ENTRY)
                    .to_string_lossy()
                    .into_owned(),
                result: EvidenceResult::Invalid,
            };
        }
    };
    let instruction_path = target_root.join(instruction_name);
    let result = wiring_result(
        provider,
        source_root,
        target_root,
        &instruction_path,
        expected_digest,
        flags,
    );
    DetectionEvidence {
        kind: EvidenceKind::ManagedFile,
        value: instruction_path.to_string_lossy().into_owned(),
        result,
    }
}

/// opencode reads its wiring from the XDG config under the home directory,
/// which deploy writes regardless of the target base.
fn inspect_opencode_wiring(
    home: &Path,
    target_root: &Path,
    expected_digest: &str,
    flags: &mut DetectionFlags,
) -> DetectionEvidence {
    let config_path = home.join(".config/opencode/opencode.json");
    let result = match inspect_relative_path(home, ".config/opencode/opencode.json") {
        PathInspection::Symlink(_) => {
            flags.record(
                IssueSeverity::Modified,
                RecommendedAction::Review,
                target_root,
            );
            EvidenceResult::Modified
        }
        PathInspection::Unreadable(_) => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            EvidenceResult::Unreadable
        }
        PathInspection::Safe => {
            opencode_wiring_result(&config_path, expected_digest, target_root, flags)
        }
    };
    DetectionEvidence {
        kind: EvidenceKind::ManagedFile,
        value: config_path.to_string_lossy().into_owned(),
        result,
    }
}

fn opencode_wiring_result(
    config_path: &Path,
    expected_digest: &str,
    target_root: &Path,
    flags: &mut DetectionFlags,
) -> EvidenceResult {
    let content = match fs::read_to_string(config_path) {
        Ok(content) => content,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            return EvidenceResult::Missing;
        }
        Err(_) => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            return EvidenceResult::Unreadable;
        }
    };
    let Ok(document) = serde_json::from_str::<serde_json::Value>(&content) else {
        flags.record(
            IssueSeverity::NeedsRepair,
            RecommendedAction::Review,
            target_root,
        );
        return EvidenceResult::Invalid;
    };
    let Some(instructions) = document
        .get("instructions")
        .and_then(serde_json::Value::as_array)
    else {
        flags.record(
            IssueSeverity::NeedsRepair,
            RecommendedAction::Review,
            target_root,
        );
        return EvidenceResult::Missing;
    };
    let current = instructions
        .iter()
        .filter_map(serde_json::Value::as_str)
        .any(|instruction| {
            manifest::content_sha256(&format!("instructions:{instruction}")) == expected_digest
        });
    if current {
        EvidenceResult::Current
    } else {
        flags.record(
            IssueSeverity::NeedsRepair,
            RecommendedAction::Review,
            target_root,
        );
        EvidenceResult::Missing
    }
}

fn wiring_result(
    provider: &str,
    source_root: &Path,
    target_root: &Path,
    instruction_path: &Path,
    expected_digest: &str,
    flags: &mut DetectionFlags,
) -> EvidenceResult {
    match inspect_one_path(instruction_path) {
        PathInspection::Symlink(_) | PathInspection::Unreadable(_) => {
            flags.record(
                IssueSeverity::Modified,
                RecommendedAction::Review,
                target_root,
            );
            return EvidenceResult::Modified;
        }
        PathInspection::Safe => {}
    }
    let content = match fs::read_to_string(instruction_path) {
        Ok(content) => content,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            return EvidenceResult::Missing;
        }
        Err(_) => {
            flags.record(
                IssueSeverity::Modified,
                RecommendedAction::Review,
                target_root,
            );
            return EvidenceResult::Modified;
        }
    };
    let Some(digest) = managed_wiring_digest(&content) else {
        flags.record(
            IssueSeverity::NeedsRepair,
            RecommendedAction::Review,
            target_root,
        );
        return EvidenceResult::Missing;
    };
    if digest != expected_digest {
        flags.record(
            IssueSeverity::Modified,
            RecommendedAction::Review,
            target_root,
        );
        return EvidenceResult::Modified;
    }
    match build_wiring_digest(source_root, provider) {
        Ok(BuildWiring::Unavailable) => EvidenceResult::Current,
        Ok(BuildWiring::Absent) => {
            flags.record(
                IssueSeverity::Outdated,
                RecommendedAction::Install,
                target_root,
            );
            EvidenceResult::Outdated
        }
        Ok(BuildWiring::Digest(digest)) => {
            if digest == expected_digest {
                EvidenceResult::Current
            } else {
                flags.record(
                    IssueSeverity::Outdated,
                    RecommendedAction::Install,
                    target_root,
                );
                EvidenceResult::Outdated
            }
        }
        Err(_) => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target_root,
            );
            EvidenceResult::Unreadable
        }
    }
}

#[must_use]
pub fn managed_wiring_digest(content: &str) -> Option<String> {
    let start = content.find(WIRING_BEGIN_MARKER)? + WIRING_BEGIN_MARKER.len();
    let end = content[start..].find(WIRING_END_MARKER)? + start;
    let block = content[start..end]
        .strip_prefix("\n\n")?
        .strip_suffix('\n')?;
    Some(manifest::content_sha256(block))
}

enum BuildWiring {
    Unavailable,
    Absent,
    Digest(String),
}

fn build_wiring_digest(source_root: &Path, provider: &str) -> Result<BuildWiring, PathBuf> {
    let provider_root = source_root.join("build").join(provider);
    match inspect_relative_path(source_root, &format!("build/{provider}")) {
        PathInspection::Safe => {}
        PathInspection::Symlink(path) | PathInspection::Unreadable(path) => return Err(path),
    }
    if !provider_root.is_dir() {
        return Ok(BuildWiring::Unavailable);
    }
    let rules_root = provider_root.join("rules");
    match inspect_relative_path(source_root, &format!("build/{provider}/rules")) {
        PathInspection::Safe => {}
        PathInspection::Symlink(path) | PathInspection::Unreadable(path) => return Err(path),
    }
    if !rules_root.is_dir() {
        return Ok(BuildWiring::Absent);
    }
    render_wiring_block(&rules_root).map(|block| {
        block.map_or(BuildWiring::Absent, |block| {
            BuildWiring::Digest(manifest::content_sha256(&block))
        })
    })
}

fn render_wiring_block(rules_root: &Path) -> Result<Option<String>, PathBuf> {
    let entries = fs::read_dir(rules_root).map_err(|_| rules_root.to_path_buf())?;
    let mut rules = BTreeMap::new();
    for entry in entries {
        let entry = entry.map_err(|_| rules_root.to_path_buf())?;
        let path = entry.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("md") {
            continue;
        }
        let file_type = entry.file_type().map_err(|_| path.clone())?;
        if file_type.is_symlink() || !file_type.is_file() {
            return Err(path);
        }
        let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        let body = fs::read_to_string(&path).map_err(|_| path.clone())?;
        rules.insert(stem.to_string(), body);
    }
    if rules.is_empty() {
        return Ok(None);
    }
    let mut block = String::from("# Rules\n");
    for (stem, body) in rules {
        block.push_str("\n## ");
        block.push_str(&stem);
        block.push_str("\n\n");
        block.push_str(body.trim_end_matches('\n'));
        block.push('\n');
    }
    Ok(Some(block))
}

#[allow(clippy::too_many_arguments)]
fn inspect_build_tree(
    provider: &str,
    config: &ProviderConfig,
    source_root: &Path,
    target_base: &Path,
    manifests: &BTreeMap<PathBuf, BTreeMap<String, manifest::ManifestEntry>>,
    flags: &mut DetectionFlags,
    evidence: &mut Vec<DetectionEvidence>,
) {
    let build_root = source_root.join("build").join(provider);
    match inspect_relative_path(source_root, &format!("build/{provider}")) {
        PathInspection::Safe => {}
        PathInspection::Symlink(path) | PathInspection::Unreadable(path) => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                &resolve_target(target_base, config.default_target()),
            );
            evidence.push(unreadable_build_evidence(&path));
            return;
        }
    }
    if !build_root.is_dir() {
        return;
    }

    let wired_codex = config.default_target() == ".codex"
        && manifests
            .get(&resolve_target(target_base, config.default_target()))
            .is_some_and(|entries| entries.contains_key(VIRTUAL_WIRING_ENTRY));
    let kinds = if source_root.join(".rune").is_file() {
        ContentKind::DECK_ALL
    } else {
        ContentKind::ALL
    };
    let mut build_keys = BTreeSet::new();
    for kind in kinds.iter().copied() {
        if wired_codex && kind == ContentKind::Rules {
            continue;
        }
        inspect_build_kind(
            config,
            target_base,
            &build_root,
            kind,
            manifests,
            &mut build_keys,
            flags,
            evidence,
        );
    }
    inspect_removed_build_files(
        provider,
        config,
        source_root,
        target_base,
        manifests,
        &build_keys,
        wired_codex,
        flags,
        evidence,
    );
}

#[allow(clippy::too_many_arguments)]
fn inspect_build_kind(
    config: &ProviderConfig,
    target_base: &Path,
    build_root: &Path,
    kind: ContentKind,
    manifests: &BTreeMap<PathBuf, BTreeMap<String, manifest::ManifestEntry>>,
    build_keys: &mut BTreeSet<(PathBuf, String)>,
    flags: &mut DetectionFlags,
    evidence: &mut Vec<DetectionEvidence>,
) {
    let kind_root = build_root.join(kind.as_str());
    match fs::symlink_metadata(&kind_root) {
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return,
        Err(_) => {
            let target = resolve_target(target_base, config.target_for_kind(kind));
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                &target,
            );
            evidence.push(unreadable_build_evidence(&kind_root));
            return;
        }
    }
    let files = match collect_regular_files(&kind_root) {
        Ok(files) => files,
        Err(path) => {
            let target = resolve_target(target_base, config.target_for_kind(kind));
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                &target,
            );
            evidence.push(unreadable_build_evidence(&path));
            return;
        }
    };
    let target = resolve_target(target_base, config.target_for_kind(kind));
    for build_path in files {
        if kind != ContentKind::Hooks
            && build_path
                .extension()
                .and_then(|extension| extension.to_str())
                == Some("yaml")
        {
            continue;
        }
        let Ok(relative) = build_path.strip_prefix(&kind_root) else {
            continue;
        };
        let key = format!("{kind}/{}", relative.to_string_lossy());
        build_keys.insert((target.clone(), key.clone()));
        inspect_build_file(
            &build_path,
            &target,
            &key,
            manifests.get(&target).and_then(|entries| entries.get(&key)),
            flags,
            evidence,
        );
    }
}

fn inspect_build_file(
    build_path: &Path,
    target: &Path,
    relative: &str,
    entry: Option<&manifest::ManifestEntry>,
    flags: &mut DetectionFlags,
    evidence: &mut Vec<DetectionEvidence>,
) {
    let deployed_path = target.join(relative);
    let Some(entry) = entry else {
        flags.record(IssueSeverity::Outdated, RecommendedAction::Install, target);
        evidence.push(DetectionEvidence {
            kind: EvidenceKind::ManagedFile,
            value: deployed_path.to_string_lossy().into_owned(),
            result: EvidenceResult::Outdated,
        });
        return;
    };
    if !valid_digest(&entry.fingerprint) {
        return;
    }
    match read_regular_file(build_path) {
        Ok(bytes) if manifest::content_sha256_bytes(&bytes) == entry.fingerprint => {}
        Ok(_) => {
            flags.record(IssueSeverity::Outdated, RecommendedAction::Install, target);
            evidence.push(DetectionEvidence {
                kind: EvidenceKind::ManagedFile,
                value: deployed_path.to_string_lossy().into_owned(),
                result: EvidenceResult::Outdated,
            });
        }
        Err(_) => {
            flags.record(
                IssueSeverity::NeedsRepair,
                RecommendedAction::Review,
                target,
            );
            evidence.push(unreadable_build_evidence(build_path));
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn inspect_removed_build_files(
    provider: &str,
    config: &ProviderConfig,
    source_root: &Path,
    target_base: &Path,
    manifests: &BTreeMap<PathBuf, BTreeMap<String, manifest::ManifestEntry>>,
    build_keys: &BTreeSet<(PathBuf, String)>,
    wired_codex: bool,
    flags: &mut DetectionFlags,
    evidence: &mut Vec<DetectionEvidence>,
) {
    for (target, entries) in manifests {
        for relative in entries.keys() {
            if relative == VIRTUAL_WIRING_ENTRY
                || generated_plugin_file(config, relative)
                || (wired_codex && relative.starts_with("rules/"))
                || expected_target(config, target_base, relative).as_ref() != Some(target)
            {
                continue;
            }
            if !build_keys.contains(&(target.clone(), relative.clone())) {
                flags.record(IssueSeverity::Outdated, RecommendedAction::Install, target);
                let build_path = source_root.join("build").join(provider).join(relative);
                evidence.push(DetectionEvidence {
                    kind: EvidenceKind::ManagedFile,
                    value: build_path.to_string_lossy().into_owned(),
                    result: EvidenceResult::Outdated,
                });
            }
        }
    }
}

fn generated_plugin_file(config: &ProviderConfig, relative: &str) -> bool {
    config.plugin.is_some() && matches!(relative, "hooks/hooks.json" | ".claude-plugin/plugin.json")
}

fn unreadable_build_evidence(path: &Path) -> DetectionEvidence {
    DetectionEvidence {
        kind: EvidenceKind::ManagedFile,
        value: path.to_string_lossy().into_owned(),
        result: EvidenceResult::Unreadable,
    }
}

fn collect_regular_files(root: &Path) -> Result<Vec<PathBuf>, PathBuf> {
    let metadata = fs::symlink_metadata(root).map_err(|_| root.to_path_buf())?;
    if metadata.is_symlink() || !metadata.is_dir() {
        return Err(root.to_path_buf());
    }
    let mut files = Vec::new();
    collect_regular_files_recursive(root, &mut files)?;
    files.sort();
    Ok(files)
}

fn collect_regular_files_recursive(
    directory: &Path,
    files: &mut Vec<PathBuf>,
) -> Result<(), PathBuf> {
    let entries = fs::read_dir(directory).map_err(|_| directory.to_path_buf())?;
    for entry in entries {
        let entry = entry.map_err(|_| directory.to_path_buf())?;
        let path = entry.path();
        let file_type = entry.file_type().map_err(|_| path.clone())?;
        if file_type.is_symlink() {
            return Err(path);
        }
        if file_type.is_dir() {
            collect_regular_files_recursive(&path, files)?;
        } else if file_type.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

fn is_managed_relative(relative: &str) -> bool {
    let path = Path::new(relative);
    !path.as_os_str().is_empty()
        && path
            .components()
            .all(|component| matches!(component, Component::Normal(_)))
        && path
            .components()
            .next()
            .and_then(|component| match component {
                Component::Normal(name) => name.to_str(),
                _ => None,
            })
            .is_some_and(|name| MANAGED_DIRECTORIES.contains(&name) || name == ".claude-plugin")
}

fn read_regular_file(path: &Path) -> Result<Vec<u8>, std::io::Error> {
    let metadata = fs::symlink_metadata(path)?;
    if metadata.is_symlink() || !metadata.is_file() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "path is not a regular file",
        ));
    }
    fs::read(path)
}

fn resolve_target(base: &Path, target: &str) -> PathBuf {
    let target = Path::new(target);
    if target.is_absolute() {
        target.to_path_buf()
    } else {
        base.join(target)
    }
}

fn executable_on_path(executable: &str, search_path: Option<&OsStr>) -> bool {
    let Some(search_path) = search_path else {
        return false;
    };
    std::env::split_paths(search_path).any(|directory| is_executable(&directory.join(executable)))
}

#[cfg(unix)]
fn is_executable(path: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt as _;

    fs::metadata(path)
        .is_ok_and(|metadata| metadata.is_file() && metadata.permissions().mode() & 0o111 != 0)
}

#[cfg(not(unix))]
fn is_executable(path: &Path) -> bool {
    path.is_file()
}
